modLoader = "javafml"
loaderVersion = "[${forge_major_version},)"
issueTrackerURL = "https://github.com/cofh/feedback"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "omgourd"
version = "${file.jarVersion}"
displayName = "Oh My Gourd"
updateJSONURL = "https://raw.github.com/cofh/version/main/omgourd/update.json"
displayURL = "https://teamcofh.com/"
logoFile = "logo.png"
credits = "Team CoFH"
authors = "King Lemming, Endergized"
description = '''
Adds a lot more carvings for Pumpkins and Jack o'Lanterns.

Suitable for both lightly and heavily modded worlds.
'''
[[dependencies.omgourd]]
modId = "minecraft"
mandatory = true
versionRange = "1.20.1"
ordering = "AFTER"
side = "BOTH"

[[dependencies.omgourd]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.omgourd]]
modId = "cofh_core"
mandatory = true
versionRange = "${cofh_core_version_range}"
ordering = "AFTER"
side = "BOTH"