modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/cofh/feedback"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "omgourd"
version = "${file.jarVersion}"
displayName = "Oh My Gourd"
updateJSONURL = "https://raw.github.com/cofh/version/master/omgourd/update.json"
displayURL = "https://teamcofh.com/"
logoFile = "logo.png"
credits = "Team CoFH"
authors = "King Lemming, Endergized"
description = '''
Adds a lot more carvings for Pumpkins and Jack o'Lanterns.

Suitable for both lightly and heavily modded worlds.
'''
[[dependencies.omgourd]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.omgourd]]
modId = "forge"
mandatory = true
versionRange = "[36.2.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.omgourd]]
modId = "cofh_core"
mandatory = true
versionRange = "[1.3,1.4]"
ordering = "AFTER"
side = "BOTH"